### ISSUE TITLE
Script fails is not executed on the same directory

### ISSUE THREAD

**Issue by alvarow** [whereisaaron/get-aws-profile-bash#5]
Hi, really cool script!

I have found that it only works if I called it from the same directory where it lives, i.e.

```
$ ./get-aws-profile.sh
```

but if I drop the script say in `~/bin` and simply call
```
~$ get-aws-profile.sh --profile=saml
/Users/regulya/bin/get-aws-profile.sh: eval: line 41: syntax error near unexpected token `}'
/Users/regulya/bin/get-aws-profile.sh: eval: line 41: `}'
Parsing credentials file '/Users/regulya/.aws/credentials' failed
```
It fails with above error.

The same error happens if I call it with the full path, but not being on the same directory:

```
~$ ./bin/get-aws-profile.sh --profile=saml
./bin/get-aws-profile.sh: eval: line 41: syntax error near unexpected token `}'
./bin/get-aws-profile.sh: eval: line 41: `}'
Parsing credentials file '/Users/regulya/.aws/credentials' failed
```

**Comment by whereisaaron** [comment]
Hi @alvarow, thanks for trying this script. I use it my 'bin' folder without issue - running it from anywhere. I tested again now and don't get any errors. Maybe check the copy in your `bin` folder is undamaged?

Maybe also try running it from another location other that your home folder. Maybe something is your home folder is being globbed. Could be we need to add `#!/bin/bash -f` or `set -f` to disable filename globbing in the `eval`. You could test that.

**Comment by alvarow** [comment]
If I run it from within `/Users/regulya/bin` it works without a problem... I am running it on Mac, not sure if that makes a difference.

I will try the suggestion and report back.

Thanks!

**Comment by alvarow** [comment]
Boom... that did it! Thanks for the suggestion!

**Comment by whereisaaron** [comment]
Adding `-f` fixed it @alvarow? If so I might make that change permanent.

**Comment by alvarow** [comment]
It did!
